name: "Auto Deployment on EC2"

on:
  push:
      branches:
           - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "Deploying Spring Application on EC2 via SSH"
              uses: appleboy/ssh-action@v0.1.10
              with:
                 host: ${{secrets.EC2_HOST}}
                 username: ${{secrets.EC2_USER}}
                 key: ${{secrets.EC2_SSH_KEY}}
                 script: |
                   if [ ! -d "JavaSpringBoot" ]; then
                      git clone https://github.com/Ramakrishna199828/JavaSpringBoot.git
                   fi
                   cd JavaSpringBoot
                   git pull origin master
                   ./mvnw clean package
                   pkill -f "java -jar" || true
                   nohup java -jar target/*.jar > output.log 2>&1 &



